name: CI CD Pipeline

on:
  push:
    branches:
    - "*"

  workflow_dispatch:

env:
  DEV_ENV: development
  STAGE_ENV: staging
  PROD_ENV: production

jobs:
  development:
    runs-on: ubuntu-latest
    environment: $DEV_ENV
    
    steps:
    - uses: actions/checkout@v2

    - name: Run a script
      if: github.ref == 'refs/heads/$DEV_ENV'
      run: |
        echo "I am running a job in the $DEV_ENV environment"

    
    - name: Go to $STAGE_ENV
      if: github.ref != 'refs/heads/$DEV_ENV'
      run: |
        echo "Go to $STAGE_ENV"

  staging:
    runs-on: ubuntu-latest
    environment: $STAGE_ENV
    needs: development
    steps:
    - uses: actions/checkout@v2

    - name: Run a script
      if: github.ref == 'refs/heads/$STAGE_ENV' || github.ref == 'refs/heads/$DEV_ENV'
      run: |
        echo "I am running a job in the $STAGE_ENV environment"
    
    - name: Go to $PROD_ENV
      if: github.ref != 'refs/heads/$STAGE_ENV' || github.ref != 'refs/heads/$DEV_ENV'
      run: |
        echo "Go to $PROD_ENV"

  production:
    runs-on: ubuntu-latest
    environment: production
    needs: staging
    steps:
    - uses: actions/checkout@v2
    
    - name: Run a script
      if: github.ref == 'refs/heads/$PROD_ENV'
      run: |
        echo "I am running a job in the $PROD_ENV environment"
