name: CI CD Pipeline

on:
  push:
    branches:
    - master

  workflow_dispatch:

jobs:
  development:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - uses: actions/checkout@v2

    - name: Run a script
      run: |
        echo "I am running a job in the development environment"

  staging:
    runs-on: ubuntu-latest
    environment: staging
    needs: development
    steps:
    - uses: actions/checkout@v2

    - name: Run a script
      run: |
        echo "I am running a job in the staging environment"

  production:
    runs-on: ubuntu-latest
    environment: production
    needs: staging
    steps:
    - uses: actions/checkout@v2
    
    - name: Run a script
      run: |
        echo "I am running a job in the staging environment"
